package com.wzj.hengmei.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MaterialExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table m_material
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table m_material
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table m_material
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public MaterialExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table m_material
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMaterialIdIsNull() {
			addCriterion("material_id is null");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIsNotNull() {
			addCriterion("material_id is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialIdEqualTo(Integer value) {
			addCriterion("material_id =", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotEqualTo(Integer value) {
			addCriterion("material_id <>", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdGreaterThan(Integer value) {
			addCriterion("material_id >", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("material_id >=", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLessThan(Integer value) {
			addCriterion("material_id <", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLessThanOrEqualTo(Integer value) {
			addCriterion("material_id <=", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIn(List<Integer> values) {
			addCriterion("material_id in", values, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotIn(List<Integer> values) {
			addCriterion("material_id not in", values, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdBetween(Integer value1, Integer value2) {
			addCriterion("material_id between", value1, value2, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotBetween(Integer value1, Integer value2) {
			addCriterion("material_id not between", value1, value2,
					"materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialNameIsNull() {
			addCriterion("material_name is null");
			return (Criteria) this;
		}

		public Criteria andMaterialNameIsNotNull() {
			addCriterion("material_name is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialNameEqualTo(String value) {
			addCriterion("material_name =", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotEqualTo(String value) {
			addCriterion("material_name <>", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameGreaterThan(String value) {
			addCriterion("material_name >", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameGreaterThanOrEqualTo(String value) {
			addCriterion("material_name >=", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameLessThan(String value) {
			addCriterion("material_name <", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameLessThanOrEqualTo(String value) {
			addCriterion("material_name <=", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameLike(String value) {
			addCriterion("material_name like", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotLike(String value) {
			addCriterion("material_name not like", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameIn(List<String> values) {
			addCriterion("material_name in", values, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotIn(List<String> values) {
			addCriterion("material_name not in", values, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameBetween(String value1, String value2) {
			addCriterion("material_name between", value1, value2,
					"materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotBetween(String value1, String value2) {
			addCriterion("material_name not between", value1, value2,
					"materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecIsNull() {
			addCriterion("material_spec is null");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecIsNotNull() {
			addCriterion("material_spec is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecEqualTo(String value) {
			addCriterion("material_spec =", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotEqualTo(String value) {
			addCriterion("material_spec <>", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecGreaterThan(String value) {
			addCriterion("material_spec >", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecGreaterThanOrEqualTo(String value) {
			addCriterion("material_spec >=", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecLessThan(String value) {
			addCriterion("material_spec <", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecLessThanOrEqualTo(String value) {
			addCriterion("material_spec <=", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecLike(String value) {
			addCriterion("material_spec like", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotLike(String value) {
			addCriterion("material_spec not like", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecIn(List<String> values) {
			addCriterion("material_spec in", values, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotIn(List<String> values) {
			addCriterion("material_spec not in", values, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecBetween(String value1, String value2) {
			addCriterion("material_spec between", value1, value2,
					"materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotBetween(String value1, String value2) {
			addCriterion("material_spec not between", value1, value2,
					"materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityIsNull() {
			addCriterion("material_quantity is null");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityIsNotNull() {
			addCriterion("material_quantity is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityEqualTo(Integer value) {
			addCriterion("material_quantity =", value, "materialQuantity");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityNotEqualTo(Integer value) {
			addCriterion("material_quantity <>", value, "materialQuantity");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityGreaterThan(Integer value) {
			addCriterion("material_quantity >", value, "materialQuantity");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityGreaterThanOrEqualTo(Integer value) {
			addCriterion("material_quantity >=", value, "materialQuantity");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityLessThan(Integer value) {
			addCriterion("material_quantity <", value, "materialQuantity");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityLessThanOrEqualTo(Integer value) {
			addCriterion("material_quantity <=", value, "materialQuantity");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityIn(List<Integer> values) {
			addCriterion("material_quantity in", values, "materialQuantity");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityNotIn(List<Integer> values) {
			addCriterion("material_quantity not in", values, "materialQuantity");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityBetween(Integer value1,
				Integer value2) {
			addCriterion("material_quantity between", value1, value2,
					"materialQuantity");
			return (Criteria) this;
		}

		public Criteria andMaterialQuantityNotBetween(Integer value1,
				Integer value2) {
			addCriterion("material_quantity not between", value1, value2,
					"materialQuantity");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Double> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Double> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andDelFlgIsNull() {
			addCriterion("del_flg is null");
			return (Criteria) this;
		}

		public Criteria andDelFlgIsNotNull() {
			addCriterion("del_flg is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlgEqualTo(String value) {
			addCriterion("del_flg =", value, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgNotEqualTo(String value) {
			addCriterion("del_flg <>", value, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgGreaterThan(String value) {
			addCriterion("del_flg >", value, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgGreaterThanOrEqualTo(String value) {
			addCriterion("del_flg >=", value, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgLessThan(String value) {
			addCriterion("del_flg <", value, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgLessThanOrEqualTo(String value) {
			addCriterion("del_flg <=", value, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgLike(String value) {
			addCriterion("del_flg like", value, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgNotLike(String value) {
			addCriterion("del_flg not like", value, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgIn(List<String> values) {
			addCriterion("del_flg in", values, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgNotIn(List<String> values) {
			addCriterion("del_flg not in", values, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgBetween(String value1, String value2) {
			addCriterion("del_flg between", value1, value2, "delFlg");
			return (Criteria) this;
		}

		public Criteria andDelFlgNotBetween(String value1, String value2) {
			addCriterion("del_flg not between", value1, value2, "delFlg");
			return (Criteria) this;
		}

		public Criteria andInsTsIsNull() {
			addCriterion("ins_ts is null");
			return (Criteria) this;
		}

		public Criteria andInsTsIsNotNull() {
			addCriterion("ins_ts is not null");
			return (Criteria) this;
		}

		public Criteria andInsTsEqualTo(Date value) {
			addCriterion("ins_ts =", value, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsTsNotEqualTo(Date value) {
			addCriterion("ins_ts <>", value, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsTsGreaterThan(Date value) {
			addCriterion("ins_ts >", value, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsTsGreaterThanOrEqualTo(Date value) {
			addCriterion("ins_ts >=", value, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsTsLessThan(Date value) {
			addCriterion("ins_ts <", value, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsTsLessThanOrEqualTo(Date value) {
			addCriterion("ins_ts <=", value, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsTsIn(List<Date> values) {
			addCriterion("ins_ts in", values, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsTsNotIn(List<Date> values) {
			addCriterion("ins_ts not in", values, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsTsBetween(Date value1, Date value2) {
			addCriterion("ins_ts between", value1, value2, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsTsNotBetween(Date value1, Date value2) {
			addCriterion("ins_ts not between", value1, value2, "insTs");
			return (Criteria) this;
		}

		public Criteria andInsUserIsNull() {
			addCriterion("ins_user is null");
			return (Criteria) this;
		}

		public Criteria andInsUserIsNotNull() {
			addCriterion("ins_user is not null");
			return (Criteria) this;
		}

		public Criteria andInsUserEqualTo(String value) {
			addCriterion("ins_user =", value, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserNotEqualTo(String value) {
			addCriterion("ins_user <>", value, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserGreaterThan(String value) {
			addCriterion("ins_user >", value, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserGreaterThanOrEqualTo(String value) {
			addCriterion("ins_user >=", value, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserLessThan(String value) {
			addCriterion("ins_user <", value, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserLessThanOrEqualTo(String value) {
			addCriterion("ins_user <=", value, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserLike(String value) {
			addCriterion("ins_user like", value, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserNotLike(String value) {
			addCriterion("ins_user not like", value, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserIn(List<String> values) {
			addCriterion("ins_user in", values, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserNotIn(List<String> values) {
			addCriterion("ins_user not in", values, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserBetween(String value1, String value2) {
			addCriterion("ins_user between", value1, value2, "insUser");
			return (Criteria) this;
		}

		public Criteria andInsUserNotBetween(String value1, String value2) {
			addCriterion("ins_user not between", value1, value2, "insUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsIsNull() {
			addCriterion("last_upd_ts is null");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsIsNotNull() {
			addCriterion("last_upd_ts is not null");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsEqualTo(Date value) {
			addCriterion("last_upd_ts =", value, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsNotEqualTo(Date value) {
			addCriterion("last_upd_ts <>", value, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsGreaterThan(Date value) {
			addCriterion("last_upd_ts >", value, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsGreaterThanOrEqualTo(Date value) {
			addCriterion("last_upd_ts >=", value, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsLessThan(Date value) {
			addCriterion("last_upd_ts <", value, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsLessThanOrEqualTo(Date value) {
			addCriterion("last_upd_ts <=", value, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsIn(List<Date> values) {
			addCriterion("last_upd_ts in", values, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsNotIn(List<Date> values) {
			addCriterion("last_upd_ts not in", values, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsBetween(Date value1, Date value2) {
			addCriterion("last_upd_ts between", value1, value2, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdTsNotBetween(Date value1, Date value2) {
			addCriterion("last_upd_ts not between", value1, value2, "lastUpdTs");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserIsNull() {
			addCriterion("last_upd_user is null");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserIsNotNull() {
			addCriterion("last_upd_user is not null");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserEqualTo(String value) {
			addCriterion("last_upd_user =", value, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserNotEqualTo(String value) {
			addCriterion("last_upd_user <>", value, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserGreaterThan(String value) {
			addCriterion("last_upd_user >", value, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserGreaterThanOrEqualTo(String value) {
			addCriterion("last_upd_user >=", value, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserLessThan(String value) {
			addCriterion("last_upd_user <", value, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserLessThanOrEqualTo(String value) {
			addCriterion("last_upd_user <=", value, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserLike(String value) {
			addCriterion("last_upd_user like", value, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserNotLike(String value) {
			addCriterion("last_upd_user not like", value, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserIn(List<String> values) {
			addCriterion("last_upd_user in", values, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserNotIn(List<String> values) {
			addCriterion("last_upd_user not in", values, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserBetween(String value1, String value2) {
			addCriterion("last_upd_user between", value1, value2, "lastUpdUser");
			return (Criteria) this;
		}

		public Criteria andLastUpdUserNotBetween(String value1, String value2) {
			addCriterion("last_upd_user not between", value1, value2,
					"lastUpdUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table m_material
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_material
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}