package com.wzj.hengmei.entity;

import java.util.Date;

public class Material {

	/**
	 * 物料id
	 * @mbg.generated
	 */
	private Integer materialId;
	/**
	 * 物料名
	 * @mbg.generated
	 */
	private String materialName;
	/**
	 * 规格
	 * @mbg.generated
	 */
	private String materialSpec;
	/**
	 * 当前数量
	 * @mbg.generated
	 */
	private Integer materialQuantity;
	/**
	 * 单价
	 * @mbg.generated
	 */
	private Double price;
	/**
	 * 删除标识(0：正常、1：删除)
	 * @mbg.generated
	 */
	private String delFlg;
	/**
	 * 创建日期
	 * @mbg.generated
	 */
	private Date insTs;
	/**
	 * 创建者
	 * @mbg.generated
	 */
	private String insUser;
	/**
	 * 更新时间
	 * @mbg.generated
	 */
	private Date lastUpdTs;
	/**
	 * 更新者
	 * @mbg.generated
	 */
	private String lastUpdUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.material_id
	 * @return  the value of m_material.material_id
	 * @mbg.generated
	 */
	public Integer getMaterialId() {
		return materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.material_id
	 * @param materialId  the value for m_material.material_id
	 * @mbg.generated
	 */
	public void setMaterialId(Integer materialId) {
		this.materialId = materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.material_name
	 * @return  the value of m_material.material_name
	 * @mbg.generated
	 */
	public String getMaterialName() {
		return materialName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.material_name
	 * @param materialName  the value for m_material.material_name
	 * @mbg.generated
	 */
	public void setMaterialName(String materialName) {
		this.materialName = materialName == null ? null : materialName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.material_spec
	 * @return  the value of m_material.material_spec
	 * @mbg.generated
	 */
	public String getMaterialSpec() {
		return materialSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.material_spec
	 * @param materialSpec  the value for m_material.material_spec
	 * @mbg.generated
	 */
	public void setMaterialSpec(String materialSpec) {
		this.materialSpec = materialSpec == null ? null : materialSpec.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.material_quantity
	 * @return  the value of m_material.material_quantity
	 * @mbg.generated
	 */
	public Integer getMaterialQuantity() {
		return materialQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.material_quantity
	 * @param materialQuantity  the value for m_material.material_quantity
	 * @mbg.generated
	 */
	public void setMaterialQuantity(Integer materialQuantity) {
		this.materialQuantity = materialQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.price
	 * @return  the value of m_material.price
	 * @mbg.generated
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.price
	 * @param price  the value for m_material.price
	 * @mbg.generated
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.del_flg
	 * @return  the value of m_material.del_flg
	 * @mbg.generated
	 */
	public String getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.del_flg
	 * @param delFlg  the value for m_material.del_flg
	 * @mbg.generated
	 */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg == null ? null : delFlg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.ins_ts
	 * @return  the value of m_material.ins_ts
	 * @mbg.generated
	 */
	public Date getInsTs() {
		return insTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.ins_ts
	 * @param insTs  the value for m_material.ins_ts
	 * @mbg.generated
	 */
	public void setInsTs(Date insTs) {
		this.insTs = insTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.ins_user
	 * @return  the value of m_material.ins_user
	 * @mbg.generated
	 */
	public String getInsUser() {
		return insUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.ins_user
	 * @param insUser  the value for m_material.ins_user
	 * @mbg.generated
	 */
	public void setInsUser(String insUser) {
		this.insUser = insUser == null ? null : insUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.last_upd_ts
	 * @return  the value of m_material.last_upd_ts
	 * @mbg.generated
	 */
	public Date getLastUpdTs() {
		return lastUpdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.last_upd_ts
	 * @param lastUpdTs  the value for m_material.last_upd_ts
	 * @mbg.generated
	 */
	public void setLastUpdTs(Date lastUpdTs) {
		this.lastUpdTs = lastUpdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_material.last_upd_user
	 * @return  the value of m_material.last_upd_user
	 * @mbg.generated
	 */
	public String getLastUpdUser() {
		return lastUpdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_material.last_upd_user
	 * @param lastUpdUser  the value for m_material.last_upd_user
	 * @mbg.generated
	 */
	public void setLastUpdUser(String lastUpdUser) {
		this.lastUpdUser = lastUpdUser == null ? null : lastUpdUser.trim();
	}
}