package com.wzj.hengmei.entity;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_info.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_info.authority
     *
     * @mbggenerated
     */
    private String authority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_info.del_flg
     *
     * @mbggenerated
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_info.ins_ts
     *
     * @mbggenerated
     */
    private Date insTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_info.ins_user
     *
     * @mbggenerated
     */
    private String insUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_info.last_upd_ts
     *
     * @mbggenerated
     */
    private Date lastUpdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_info.last_upd_user
     *
     * @mbggenerated
     */
    private String lastUpdUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_info.user_id
     *
     * @return the value of m_user_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_info.user_id
     *
     * @param userId the value for m_user_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_info.user_name
     *
     * @return the value of m_user_info.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_info.user_name
     *
     * @param userName the value for m_user_info.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_info.password
     *
     * @return the value of m_user_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_info.password
     *
     * @param password the value for m_user_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_info.authority
     *
     * @return the value of m_user_info.authority
     *
     * @mbggenerated
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_info.authority
     *
     * @param authority the value for m_user_info.authority
     *
     * @mbggenerated
     */
    public void setAuthority(String authority) {
        this.authority = authority == null ? null : authority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_info.del_flg
     *
     * @return the value of m_user_info.del_flg
     *
     * @mbggenerated
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_info.del_flg
     *
     * @param delFlg the value for m_user_info.del_flg
     *
     * @mbggenerated
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg == null ? null : delFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_info.ins_ts
     *
     * @return the value of m_user_info.ins_ts
     *
     * @mbggenerated
     */
    public Date getInsTs() {
        return insTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_info.ins_ts
     *
     * @param insTs the value for m_user_info.ins_ts
     *
     * @mbggenerated
     */
    public void setInsTs(Date insTs) {
        this.insTs = insTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_info.ins_user
     *
     * @return the value of m_user_info.ins_user
     *
     * @mbggenerated
     */
    public String getInsUser() {
        return insUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_info.ins_user
     *
     * @param insUser the value for m_user_info.ins_user
     *
     * @mbggenerated
     */
    public void setInsUser(String insUser) {
        this.insUser = insUser == null ? null : insUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_info.last_upd_ts
     *
     * @return the value of m_user_info.last_upd_ts
     *
     * @mbggenerated
     */
    public Date getLastUpdTs() {
        return lastUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_info.last_upd_ts
     *
     * @param lastUpdTs the value for m_user_info.last_upd_ts
     *
     * @mbggenerated
     */
    public void setLastUpdTs(Date lastUpdTs) {
        this.lastUpdTs = lastUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_info.last_upd_user
     *
     * @return the value of m_user_info.last_upd_user
     *
     * @mbggenerated
     */
    public String getLastUpdUser() {
        return lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_info.last_upd_user
     *
     * @param lastUpdUser the value for m_user_info.last_upd_user
     *
     * @mbggenerated
     */
    public void setLastUpdUser(String lastUpdUser) {
        this.lastUpdUser = lastUpdUser == null ? null : lastUpdUser.trim();
    }
}