package com.wzj.hengmei.mapper;

import com.wzj.hengmei.entity.Codename;
import com.wzj.hengmei.entity.CodenameExample;
import com.wzj.hengmei.entity.CodenameKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodenameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    int countByExample(CodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    int deleteByExample(CodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CodenameKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    int insert(Codename record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    int insertSelective(Codename record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    List<Codename> selectByExample(CodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    Codename selectByPrimaryKey(CodenameKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Codename record, @Param("example") CodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Codename record, @Param("example") CodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Codename record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_codename
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Codename record);
}