package com.wzj.hengmei.mapper;

import com.wzj.hengmei.entity.Material;
import com.wzj.hengmei.entity.MaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MaterialMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	int countByExample(MaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	int deleteByExample(MaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer materialId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	int insert(Material record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	int insertSelective(Material record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	List<Material> selectByExample(MaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	Material selectByPrimaryKey(Integer materialId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Material record,
			@Param("example") MaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Material record,
			@Param("example") MaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Material record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_material
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Material record);
}